import SwiftUI

/// Brand colors and marks. Assets are generated by scripts/generate_brand_assets.py from brand/.
enum Brand {
    static let green = Color("BrandGreen")
    static let cream = Color("BrandCream")
    /// Text and icons drawn on the accent color (white in light mode, forest green in dark mode).
    static let onAccent = Color("OnAccent")
}

/// The "CHOSS" wordmark. Forest green in light mode, cream in dark mode.
struct WordmarkView: View {
    var height: CGFloat = 24

    var body: some View {
        Image("Wordmark")
            .resizable()
            .interpolation(.high)
            .scaledToFit()
            .frame(height: height)
            .accessibilityLabel("CHOSS")
            .accessibilityAddTraits(.isHeader)
    }
}

/// The climbing-hold mark, tinted with the current foreground style.
struct HoldMarkView: View {
    var size: CGFloat = 24

    var body: some View {
        Image("HoldMarkLarge")
            .resizable()
            .renderingMode(.template)
            .interpolation(.high)
            .scaledToFit()
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

/// The like icon: a flexed bicep, outlined or filled (liked). Tint it like an SF Symbol.
/// Pops briefly when it fills.
struct FlexIcon: View {
    var filled: Bool
    var size: CGFloat = 24

    @State private var pop = false

    var body: some View {
        Image(filled ? "FlexMarkFill" : "FlexMark")
            .resizable()
            .renderingMode(.template)
            .interpolation(.high)
            .scaledToFit()
            .frame(width: size, height: size)
            .scaleEffect(pop ? 1.25 : 1)
            .onChange(of: filled) { _, isFilled in
                guard isFilled else { return }
                withAnimation(.spring(response: 0.2, dampingFraction: 0.5)) { pop = true }
                withAnimation(.spring(response: 0.3, dampingFraction: 0.6).delay(0.15)) { pop = false }
            }
            .accessibilityHidden(true)
    }
}

/// Played over a video when it's liked: a bicep pops in, gives a quick flex (a small curl
/// back and forth), then floats up and fades. Invisible between likes; never blocks taps.
struct LikeBurst: View {
    /// Change it to play the animation once.
    let trigger: Int

    private struct Frame {
        var scale = 0.4
        var angle = 0.0
        var lift = 0.0
        var opacity = 0.0
    }

    var body: some View {
        Image("FlexMarkFill")
            .resizable()
            .renderingMode(.template)
            .interpolation(.high)
            .scaledToFit()
            .frame(width: 84, height: 84)
            .foregroundStyle(.white)
            .shadow(color: .black.opacity(0.3), radius: 8, y: 2)
            .keyframeAnimator(initialValue: Frame(), trigger: trigger) { content, frame in
                content
                    .scaleEffect(frame.scale)
                    .rotationEffect(.degrees(frame.angle), anchor: .bottom)
                    .offset(y: frame.lift)
                    .opacity(frame.opacity)
            } keyframes: { _ in
                KeyframeTrack(\.scale) {
                    SpringKeyframe(1.1, duration: 0.22, spring: .bouncy)
                    SpringKeyframe(1.0, duration: 0.18)
                    LinearKeyframe(1.0, duration: 0.3)
                    CubicKeyframe(0.85, duration: 0.3)
                }
                KeyframeTrack(\.angle) {
                    LinearKeyframe(0, duration: 0.2)
                    CubicKeyframe(-12, duration: 0.12)
                    CubicKeyframe(8, duration: 0.12)
                    CubicKeyframe(0, duration: 0.14)
                }
                KeyframeTrack(\.lift) {
                    LinearKeyframe(0, duration: 0.7)
                    CubicKeyframe(-28, duration: 0.3)
                }
                KeyframeTrack(\.opacity) {
                    LinearKeyframe(1, duration: 0.08)
                    LinearKeyframe(1, duration: 0.62)
                    LinearKeyframe(0, duration: 0.3)
                }
            }
            .allowsHitTesting(false)
            .accessibilityHidden(true)
    }
}

/// Quiet sign-off at the bottom of scrolling pages.
struct BrandFooter: View {
    var message: String? = nil

    var body: some View {
        VStack(spacing: 8) {
            if let message {
                Text(message)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            WordmarkView(height: 18)
                .opacity(0.35)
        }
        .frame(maxWidth: .infinity)
        .padding(.top, 24)
        .padding(.bottom, 32)
    }
}

/// Shown while the app loads its data.
struct SplashView: View {
    var body: some View {
        ZStack {
            Brand.green.ignoresSafeArea()
            VStack(spacing: 24) {
                HoldMarkView(size: 120)
                    .foregroundStyle(Brand.cream)
                WordmarkView(height: 44)
                    // Always the cream variant on the green background.
                    .environment(\.colorScheme, .dark)
                ProgressView()
                    .tint(Brand.cream)
                    .padding(.top, 8)
            }
        }
    }
}

#Preview("Splash") {
    SplashView()
}

#Preview("Footer") {
    BrandFooter(message: "You're all caught up")
}
