import SwiftUI

/// Brand colors and marks. Assets are generated by scripts/generate_brand_assets.py from brand/.
enum Brand {
    static let green = Color("BrandGreen")
    static let cream = Color("BrandCream")
    /// Text and icons drawn on the accent color (white in light mode, forest green in dark mode).
    static let onAccent = Color("OnAccent")
}

/// The "CHOSS" wordmark. Forest green in light mode, cream in dark mode.
struct WordmarkView: View {
    var height: CGFloat = 24

    var body: some View {
        Image("Wordmark")
            .resizable()
            .interpolation(.high)
            .scaledToFit()
            .frame(height: height)
            .accessibilityLabel("CHOSS")
            .accessibilityAddTraits(.isHeader)
    }
}

/// The climbing-hold mark, tinted with the current foreground style.
struct HoldMarkView: View {
    var size: CGFloat = 24

    var body: some View {
        Image("HoldMarkLarge")
            .resizable()
            .renderingMode(.template)
            .interpolation(.high)
            .scaledToFit()
            .frame(width: size, height: size)
            .accessibilityHidden(true)
    }
}

/// Quiet sign-off at the bottom of scrolling pages.
struct BrandFooter: View {
    var message: String? = nil

    var body: some View {
        VStack(spacing: 8) {
            if let message {
                Text(message)
                    .font(.footnote)
                    .foregroundStyle(.secondary)
            }
            WordmarkView(height: 18)
                .opacity(0.35)
        }
        .frame(maxWidth: .infinity)
        .padding(.top, 24)
        .padding(.bottom, 32)
    }
}

/// Shown while the app loads its data.
struct SplashView: View {
    var body: some View {
        ZStack {
            Brand.green.ignoresSafeArea()
            VStack(spacing: 24) {
                HoldMarkView(size: 120)
                    .foregroundStyle(Brand.cream)
                WordmarkView(height: 44)
                    // Always the cream variant on the green background.
                    .environment(\.colorScheme, .dark)
                ProgressView()
                    .tint(Brand.cream)
                    .padding(.top, 8)
            }
        }
    }
}

#Preview("Splash") {
    SplashView()
}

#Preview("Footer") {
    BrandFooter(message: "You're all caught up")
}
