#!/usr/bin/env python3
"""Generate backend seed SQL from the app's own data, so server and app agree.

  python3 scripts/export_backend_seed.py

Writes:
  supabase/migrations/20261001000100_grades.sql   the grade scales (same order and conversions
                                                  as CHOSS/Models/Grade.swift)
  supabase/seed.sql                               the bundled US gyms and crags
                                                  (CHOSS/Resources/*.json)

Place ids become UUIDs derived from the app's ids (md5 of "place:<id>"), so re-running is
idempotent and the old id is kept as external_id.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "supabase" / "migrations"

# --- Grades (mirror CHOSS/Models/Grade.swift) -----------------------------------------------

def grade_lists():
    font = ["3", "4", "4+", "5", "5+"] + [f"{n}{s}" for n in "678" for s in ["A", "A+", "B", "B+", "C", "C+"]] + ["9A"]
    return {
        "vScale": ["VB"] + [f"V{i}" for i in range(18)],
        "font": font,
        "yds": [f"5.{i}" for i in range(5, 10)] + [f"5.{n}{l}" for n in range(10, 16) for l in "abcd"],
        "french": ["4a", "4b", "4c", "5a", "5b", "5c"] + [f"{n}{s}" for n in range(6, 10) for s in ["a", "a+", "b", "b+", "c", "c+"]],
        "british": ["Mod", "Diff", "VDiff", "HVD", "Sev", "HS", "VS", "HVS"] + [f"E{i}" for i in range(1, 12)],
        "waterIce": ["WI1", "WI2", "WI2+", "WI3", "WI3+", "WI4", "WI4+", "WI5", "WI5+", "WI6", "WI6+", "WI7"],
        "mixed": [f"M{i}" for i in range(1, 15)],
    }

FONT_TO_V = {
    "3": "VB", "4": "V0", "4+": "V0", "5": "V1", "5+": "V2",
    "6A": "V3", "6A+": "V3", "6B": "V4", "6B+": "V4", "6C": "V5", "6C+": "V5",
    "7A": "V6", "7A+": "V7", "7B": "V8", "7B+": "V8", "7C": "V9", "7C+": "V10",
    "8A": "V11", "8A+": "V12", "8B": "V13", "8B+": "V14", "8C": "V15", "8C+": "V16", "9A": "V17",
}
FRENCH_TO_YDS = {
    "4a": "5.5", "4b": "5.6", "4c": "5.7", "5a": "5.8", "5b": "5.9", "5c": "5.10a",
    "6a": "5.10b", "6a+": "5.10d", "6b": "5.11a", "6b+": "5.11b", "6c": "5.11c", "6c+": "5.11d",
    "7a": "5.12a", "7a+": "5.12b", "7b": "5.12c", "7b+": "5.12d", "7c": "5.13a", "7c+": "5.13b",
    "8a": "5.13c", "8a+": "5.13d", "8b": "5.14a", "8b+": "5.14b", "8c": "5.14c", "8c+": "5.14d",
    "9a": "5.15a", "9a+": "5.15b", "9b": "5.15c", "9b+": "5.15d", "9c": "5.15d", "9c+": "5.15d",
}
BRITISH_TO_YDS = {
    "Mod": "5.5", "Diff": "5.5", "VDiff": "5.6", "HVD": "5.6", "Sev": "5.7", "HS": "5.8",
    "VS": "5.9", "HVS": "5.10a", "E1": "5.10c", "E2": "5.11a", "E3": "5.11c", "E4": "5.12a",
    "E5": "5.12c", "E6": "5.13a", "E7": "5.13c", "E8": "5.14a", "E9": "5.14c", "E10": "5.15a",
    "E11": "5.15c",
}


def q(text):
    return "'" + str(text).replace("'", "''") + "'"


def grades_sql():
    lists = grade_lists()
    rows = []
    for system, values in lists.items():
        for rank, value in enumerate(values):
            if system in ("vScale", "yds", "waterIce", "mixed"):
                comp_system, comp_value = system, value  # mixed is only compared with mixed
            elif system == "font":
                comp_system, comp_value = "vScale", FONT_TO_V.get(value)
            elif system == "french":
                comp_system, comp_value = "yds", FRENCH_TO_YDS.get(value)
            else:  # british
                comp_system, comp_value = "yds", BRITISH_TO_YDS.get(value)
            comp_rank = lists[comp_system].index(comp_value) if comp_value in lists.get(comp_system, []) else None
            rows.append(f"  ({q(system)}, {q(value)}, {rank}, {q(comp_system)}, "
                        f"{comp_rank if comp_rank is not None else 'null'})")
    return (
        "-- Generated by scripts/export_backend_seed.py from CHOSS/Models/Grade.swift. Do not edit.\n"
        "-- Every grade with its position on its own scale (rank) and on the scale it's compared on\n"
        "-- (Font -> V-scale, French / British -> YDS; WI and M compare with themselves).\n\n"
        "insert into public.grades (system, value, rank, comparable_system, comparable_rank) values\n"
        + ",\n".join(rows)
        + "\non conflict (system, value) do update set rank = excluded.rank,\n"
          "  comparable_system = excluded.comparable_system, comparable_rank = excluded.comparable_rank;\n"
    )


# --- Places ---------------------------------------------------------------------------------

def places_sql():
    places = []
    for name in ("us_climbing_gyms.json", "us_climbing_areas.json"):
        places += json.loads((ROOT / "CHOSS" / "Resources" / name).read_text())
    rows = []
    for p in places:
        disciplines = "array[" + ", ".join(q(d) for d in p.get("disciplines", [])) + "]::public.discipline[]"
        rows.append(
            f"  (md5({q('place:' + p['id'])})::uuid, {q(p['id'])}, {q(p['name'])}, {q(p['kind'])}, "
            f"{q(p.get('city', ''))}, {q(p.get('region', ''))}, {q(p.get('country', ''))}, "
            f"{p['latitude']}, {p['longitude']}, {disciplines}, {q(p.get('about', ''))}, "
            f"{q(p.get('source', 'curated'))}, {str(bool(p.get('isVerified', True))).lower()})"
        )
    header = (
        "-- Generated by scripts/export_backend_seed.py from the app's bundled directory. Do not edit.\n"
        f"-- {len(places)} US gyms and crags.\n\n"
    )
    chunks = []
    for start in range(0, len(rows), 500):
        chunks.append(
            "insert into public.places (id, external_id, name, kind, city, region, country, latitude, "
            "longitude, disciplines, about, source, is_verified) values\n"
            + ",\n".join(rows[start:start + 500])
            + "\non conflict (id) do nothing;\n"
        )
    return header + "\n".join(chunks)


if __name__ == "__main__":
    (MIGRATIONS / "20261001000100_grades.sql").write_text(grades_sql())
    (ROOT / "supabase" / "seed.sql").write_text(places_sql())
    print("Wrote grades migration and supabase/seed.sql")
