import Foundation

/// The style of climbing a send was done in.
enum ClimbDiscipline: String, Codable, CaseIterable, Identifiable, Hashable {
    case boulder
    case sport
    case trad
    case topRope
    case ice
    /// Training boards (Moon, Kilter, Tension…): graded like boulders.
    case board
    /// Free soloing: routes climbed without a rope.
    case solo
    /// Anything that isn't one of the above (deep water solo, aid, a traverse…).
    case other

    var id: Self { self }

    var displayName: String {
        switch self {
        case .boulder: "Boulder"
        case .sport: "Sport"
        case .trad: "Trad"
        case .topRope: "Top Rope"
        case .ice: "Ice"
        case .board: "Board"
        case .solo: "Solo"
        case .other: "Other"
        }
    }

    /// Asset name of the discipline's icon (hold, quickdraw, cam, top-rope anchor, ice axe), a template
    /// image tinted like an SF Symbol. `…Large` versions exist for big placements.
    /// Generated by scripts/generate_brand_assets.py from brand/discipline-icons-source.png
    /// and brand/discipline-ice-source.png.
    var iconName: String {
        switch self {
        case .boulder: "DisciplineBoulder"
        case .sport: "DisciplineSport"
        case .trad: "DisciplineTrad"
        case .topRope: "DisciplineTopRope"
        case .ice: "DisciplineIce"
        case .solo: "DisciplineSolo"
        case .board, .other: ""  // uses `systemImageName`
        }
    }

    /// SF Symbol for disciplines without a brand icon.
    var systemImageName: String? {
        switch self {
        case .board: "circle.grid.3x3.fill"  // a board's grid of holds
        case .other: "ellipsis.circle"
        default: nil
        }
    }

    var isRoped: Bool { self != .boulder && self != .board && self != .solo }

    /// Board problems have names wherever they're climbed (a gym's board included), unlike other
    /// gym climbs.
    var allowsNameAtGym: Bool { self == .board }

    /// Sensible default grading system; users can switch (e.g. Font in Europe, M for mixed).
    var defaultGradeSystem: GradeSystem { gradeSystems[0] }

    var gradeSystems: [GradeSystem] {
        switch self {
        case .boulder, .board: [.vScale, .font]
        case .sport, .topRope: [.yds, .french]
        // Trad (and soloing, usually on trad-graded routes) can also use British E grades.
        case .trad, .solo: [.yds, .french, .british]
        case .ice: [.waterIce, .mixed]
        // Could be anything, so every scale is offered.
        case .other: [.vScale, .font, .yds, .french, .british, .waterIce, .mixed]
        }
    }
}

enum GradeSystem: String, Codable, CaseIterable, Identifiable, Hashable {
    case vScale
    case font
    case yds
    case french
    /// British adjectival / E grades (Mod … HVS, E1–E11), used for trad in the UK.
    case british
    /// Water ice: WI1–WI7.
    case waterIce
    /// Mixed (rock and ice with tools): M1–M14.
    case mixed

    var id: Self { self }

    var displayName: String {
        switch self {
        case .vScale: "V-Scale"
        case .font: "Font"
        case .yds: "YDS"
        case .french: "French"
        case .british: "British (E)"
        case .waterIce: "WI"
        case .mixed: "Mixed (M)"
        }
    }

    /// Grades ordered easiest → hardest.
    var grades: [String] {
        switch self {
        case .vScale:
            return ["VB"] + (0...17).map { "V\($0)" }
        case .font:
            return ["3", "4", "4+", "5", "5+"]
                + ["6", "7", "8"].flatMap { n in ["A", "A+", "B", "B+", "C", "C+"].map { "\(n)\($0)" } }
                + ["9A"]
        case .yds:
            return (5...9).map { "5.\($0)" }
                + (10...15).flatMap { n in ["a", "b", "c", "d"].map { "5.\(n)\($0)" } }
        case .french:
            return ["4a", "4b", "4c", "5a", "5b", "5c"]
                + (6...9).flatMap { n in ["a", "a+", "b", "b+", "c", "c+"].map { "\(n)\($0)" } }
        case .british:
            return ["Mod", "Diff", "VDiff", "HVD", "Sev", "HS", "VS", "HVS"] + (1...11).map { "E\($0)" }
        case .waterIce:
            return ["WI1", "WI2", "WI2+", "WI3", "WI3+", "WI4", "WI4+", "WI5", "WI5+", "WI6", "WI6+", "WI7"]
        case .mixed:
            return (1...14).map { "M\($0)" }
        }
    }
}

struct Grade: Codable, Hashable {
    var system: GradeSystem
    var value: String

    /// Position within its system; only comparable between grades of the same system.
    var rank: Int { system.grades.firstIndex(of: value) ?? -1 }

    static func defaultGrade(for discipline: ClimbDiscipline) -> Grade {
        defaultGrade(in: discipline.defaultGradeSystem)
    }

    /// A reasonable starting point for pickers (roughly a third of the way up the scale).
    static func defaultGrade(in system: GradeSystem) -> Grade {
        let grades = system.grades
        return Grade(system: system, value: grades[grades.count / 3])
    }
}

/// Boulders, rock routes and ice are graded differently and can't be compared with each other.
enum GradeCategory: String, CaseIterable, Identifiable, Hashable {
    case boulder
    case route
    case ice

    var id: Self { self }

    var displayName: String {
        switch self {
        case .boulder: "Boulders"
        case .route: "Routes"
        case .ice: "Ice"
        }
    }

    /// Every grade in the category is converted to this scale for comparison.
    var canonicalSystem: GradeSystem {
        switch self {
        case .boulder: .vScale
        case .route: .yds
        case .ice: .waterIce
        }
    }

    /// The discipline whose icon represents the category.
    var iconDiscipline: ClimbDiscipline {
        switch self {
        case .boulder: .boulder
        case .route: .sport
        case .ice: .ice
        }
    }
}

extension GradeSystem {
    var category: GradeCategory {
        switch self {
        case .vScale, .font: .boulder
        case .yds, .french, .british: .route
        case .waterIce, .mixed: .ice
        }
    }
}

extension Grade {
    /// Approximate Font → V-scale conversion.
    private static let fontToV: [String: String] = [
        "3": "VB", "4": "V0", "4+": "V0", "5": "V1", "5+": "V2",
        "6A": "V3", "6A+": "V3", "6B": "V4", "6B+": "V4", "6C": "V5", "6C+": "V5",
        "7A": "V6", "7A+": "V7", "7B": "V8", "7B+": "V8", "7C": "V9", "7C+": "V10",
        "8A": "V11", "8A+": "V12", "8B": "V13", "8B+": "V14", "8C": "V15", "8C+": "V16", "9A": "V17",
    ]

    /// Approximate French sport → YDS conversion.
    private static let frenchToYDS: [String: String] = [
        "4a": "5.5", "4b": "5.6", "4c": "5.7", "5a": "5.8", "5b": "5.9", "5c": "5.10a",
        "6a": "5.10b", "6a+": "5.10d", "6b": "5.11a", "6b+": "5.11b", "6c": "5.11c", "6c+": "5.11d",
        "7a": "5.12a", "7a+": "5.12b", "7b": "5.12c", "7b+": "5.12d", "7c": "5.13a", "7c+": "5.13b",
        "8a": "5.13c", "8a+": "5.13d", "8b": "5.14a", "8b+": "5.14b", "8c": "5.14c", "8c+": "5.14d",
        "9a": "5.15a", "9a+": "5.15b", "9b": "5.15c", "9b+": "5.15d", "9c": "5.15d", "9c+": "5.15d",
    ]

    /// Rough British → YDS conversion. British grades also depend on protection and seriousness,
    /// so this is only for comparing on leaderboards and filters.
    private static let britishToYDS: [String: String] = [
        "Mod": "5.5", "Diff": "5.5", "VDiff": "5.6", "HVD": "5.6", "Sev": "5.7", "HS": "5.8",
        "VS": "5.9", "HVS": "5.10a", "E1": "5.10c", "E2": "5.11a", "E3": "5.11c", "E4": "5.12a",
        "E5": "5.12c", "E6": "5.13a", "E7": "5.13c", "E8": "5.14a", "E9": "5.14c", "E10": "5.15a",
        "E11": "5.15c",
    ]

    /// The same grade on its category's common scale (V-scale for boulders, YDS for routes, WI
    /// for ice), so grades from different systems can be compared. nil if it can't be converted
    /// (mixed M grades measure something different from water ice, so they aren't ranked with it).
    var canonical: Grade? {
        let converted: String?
        switch system {
        case .vScale, .yds, .waterIce: converted = value
        case .font: converted = Self.fontToV[value]
        case .french: converted = Self.frenchToYDS[value]
        case .british: converted = Self.britishToYDS[value]
        case .mixed: converted = nil
        }
        guard let converted else { return nil }
        let grade = Grade(system: system.category.canonicalSystem, value: converted)
        return grade.rank >= 0 ? grade : nil
    }
}

extension Grade {
    /// This grade on a scale shared with other systems of its kind (see `canonical`); mixed (M)
    /// grades have no equivalent and are compared only with each other.
    var comparable: Grade? {
        if let canonical { return canonical }
        return system == .mixed && rank >= 0 ? self : nil
    }
}

extension GradeRange {
    /// Whether `grade` falls in this range, comparing across systems of the same kind
    /// (a V3–V6 range includes a 6B+ boulder). Grades of another kind never match.
    func contains(_ grade: Grade) -> Bool {
        guard let target = grade.comparable,
              let from = Grade(system: system, value: low).comparable,
              let to = Grade(system: system, value: high ?? low).comparable,
              target.system == from.system else { return false }
        let bounds = min(from.rank, to.rank)...max(from.rank, to.rank)
        return bounds.contains(target.rank)
    }
}

/// A climber's self-reported ability, e.g. "V4–V6" or just "5.11a".
struct GradeRange: Codable, Hashable {
    var system: GradeSystem
    var low: String
    /// nil (or equal to `low`) means a single grade rather than a range.
    var high: String?

    var display: String {
        guard let high, high != low else { return low }
        return "\(low)–\(high)"
    }
}

/// How the climb was sent.
enum SendStyle: String, Codable, CaseIterable, Identifiable, Hashable {
    case onsight
    case flash
    case redpoint
    case repeatSend
    /// Linked a section / moves of the climb, not a full send.
    case link
    /// None of the above (an attempt, a training session…).
    case other

    var id: Self { self }

    var displayName: String {
        switch self {
        case .onsight: "Onsight"
        case .flash: "Flash"
        case .redpoint: "Send"
        case .repeatSend: "Repeat"
        case .link: "Link"
        case .other: "Other"
        }
    }

    var symbolName: String {
        switch self {
        case .onsight: "eye.fill"
        case .flash: "bolt.fill"
        case .redpoint: "checkmark.seal.fill"
        case .repeatSend: "arrow.clockwise"
        case .link: "point.3.connected.trianglepath.dotted"
        case .other: "ellipsis.circle"
        }
    }

    /// Onsight, flash, send and repeat all count as a send (no separate onsight / flash tallies).
    /// A link is a section of the climb and "Other" isn't necessarily a send, so neither counts
    /// as having sent it (leaderboards, hardest send).
    var countsAsSend: Bool { self != .link && self != .other }
}
